# Generated by Django 5.2.5 on 2025-09-08 11:05

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام هنرجو')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('registration_date', models.DateField(verbose_name='تاریخ ثبت\u200cنام')),
                ('monthly_fee', models.IntegerField(verbose_name='شهریه ماهانه (ریال)')),
            ],
            options={
                'verbose_name': 'هنرجو',
                'verbose_name_plural': 'هنرجویان',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام استاد')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('percentage_share', models.IntegerField(help_text='درصدی که استاد از هر پرداخت دریافت می\u200cکند (بین 0 تا 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد سهم استاد')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_year', models.IntegerField(default=1404, validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(1500)], verbose_name='سال آموزشی')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداختی (ریال)')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('transfer', 'انتقال بانکی')], max_length=10, verbose_name='روش پرداخت')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('for_month', core.models.PersianMonthField(choices=[('01', 'فروردین'), ('02', 'اردیبهشت'), ('03', 'خرداد'), ('04', 'تیر'), ('05', 'مرداد'), ('06', 'شهریور'), ('07', 'مهر'), ('08', 'آبان'), ('09', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=10, verbose_name='ماه آموزشی')),
                ('teacher_share', models.IntegerField(default=0, verbose_name='سهم استاد (ریال)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه\u200cشنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], max_length=1, verbose_name='روز هفته')),
                ('time', models.TimeField(verbose_name='ساعت کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='هنرجو')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'جلسه کلاس',
                'verbose_name_plural': 'جلسات کلاس',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='استاد'),
        ),
        migrations.CreateModel(
            name='TeacherSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ تسویه (ریال)')),
                ('settlement_date', models.DateField(verbose_name='تاریخ تسویه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'تسویه حساب استاد',
                'verbose_name_plural': 'تسویه حساب با اساتید',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('session_1', models.CharField(blank=True, choices=[('present', 'حاضر'), ('absent', 'غایب'), ('makeup', 'جبرانی')], max_length=10, verbose_name='جلسه ۱')),
                ('session_2', models.CharField(blank=True, choices=[('present', 'حاضر'), ('absent', 'غایب'), ('makeup', 'جبرانی')], max_length=10, verbose_name='جلسه ۲')),
                ('session_3', models.CharField(blank=True, choices=[('present', 'حاضر'), ('absent', 'غایب'), ('makeup', 'جبرانی')], max_length=10, verbose_name='جلسه ۳')),
                ('session_4', models.CharField(blank=True, choices=[('present', 'حاضر'), ('absent', 'غایب'), ('makeup', 'جبرانی')], max_length=10, verbose_name='جلسه ۴')),
                ('session_5', models.CharField(blank=True, choices=[('present', 'حاضر'), ('absent', 'غایب'), ('makeup', 'جبرانی')], max_length=10, verbose_name='جلسه ۵')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classsession', verbose_name='جلسه کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب\u200cها',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
